### ISSUE TITLE
What is the search time histogram showing? 

### ISSUE THREAD

**Issue by gcraenen** [retzkek/chiamon#16]
I'm wondering what the search time histogram is showing exactly? Is that the equivalent of the nr. of seconds for proofing a plot when farming? If not, how can you create a component that shows if the speed of plots are below the 5 and 30 second mark?

I think a lot of people don't know that the respondspeeds for proofing and answering when farming is bigger then 30 seconds and they will not earn anything.

**Comment by retzkek** [comment]
Yes, that is exactly what it shows. Each bin is a count of the the number of proof searches that happened within that amount of time (signage points for which no plots passed the filter are omitted, since that is always very quick). So if you see > 0 in the 10, 30, or +Inf buckets then yes you could potentially miss out on rewards and should look for ways to improve your farming setup.

**Comment by gcraenen** [comment]
Ok, thanks. Nice implementation!
